name: Build Apk
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android:4
    steps:
      - uses: actions/checkout@v2
      - name: Build application
        run: yarn install && cd android && chmod +x gradlew && ./gradlew assembleRelease
